ALTER TABLE news_posts ALTER COLUMN id DROP DEFAULT;
ALTER TABLE raids ALTER COLUMN id DROP DEFAULT;
ALTER TABLE streams ALTER COLUMN id DROP DEFAULT;
ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE characters ALTER COLUMN id DROP DEFAULT;
